services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: plannerpw
      POSTGRES_DB: plannerdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: . 
    container_name: backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://planner:plannerpw@db:5432/plannerdb
      JWT_SECRET: super-secret-long-random-string
      JWT_EXPIRES_IN: 7d
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pg_data:
